org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = false

# Project
version = 0.0.9
group = com.github.mahmudindev.mcmod.orenocommons
description = Unify and add common code across mod loader.

mod_id = orenocommons
mod_name = Oreno Commons
mod_authors = mahmudindev
mod_license = ARR

# General
java_version = 25
minecraft_version = 26.1

# Fabric
fabric_loom_version = 1.15.5
fabric_loader_version = 0.19.2
fabric_api_version = 0.145.1

# NeoForge
neoforge_moddev_version = 2.0.141
neoforge_loader_version = 4
neoforge_version = 0.19-beta
